title: "COVID-19 World Survey Data API"
remote_theme: pmarsceill/just-the-docs
color_scheme: color_theme
logo: "/assets/images/umd-globe.svg"
baseurl: "/COVID-19-API-Documentation"
url: "https://gisumd.github.io"
aux_links:
  "COVID-19 World Symptoms Survey":
    - "//covidmap.umd.edu"

collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/: _docs/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    docs:
      # Give the collection a name
      name: Documentation
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
