title: "COVID-19 World Survey Data API"
remote_theme: pmarsceill/just-the-docs
color_scheme: color_theme
logo: "/assets/images/umd-globe.svg"
aux_links:
  "COVID-19 World Symptoms Survey":
    - "//covidmap.umd.edu"
aux_links_new_tab: true

baseurl: "/COVID-19-API-Documentation/" # the subpath of your site, e.g. /blog
url: "https://gisumd.github.io" # the base hostname & protocol for your site, e.g. http://example.com

exclude: ["CONTRIBUTING.md", "README.md"]

footer_content: "Copyright &copy; 2020 <a href=\"https://geospatial.umd.edu\">Center for Geospatial Information Science</a>, University of Maryland, College Park."
