title: "COVID-19 World Survey Data API"
remote_theme: pmarsceill/just-the-docs
color_scheme: color_theme
logo: "/assets/images/umd-globe.svg"
aux_links:
  "COVID-19 World Symptoms Survey":
    - "//covidmap.umd.edu"
